site_name: Simpledger联盟链
pages:
  - 整体概述:
    - simpledger介绍: zhengtijieshao.md
  - 系统设计:
    - 功能模块: gongnengjiesho.md
#    - 关键特性: texingjieshao.md
    - 接口文档: api.m
    - RPC接口: rpc.md
  - 网络搭建:
    - 快速开始: run.md
version: v1.0.0
theme: readthedocs
