site_name: Simpledger联盟链
pages:
  - 整体概述:
    - simpledger介绍: zhengtijieshao.md
  - 系统设计:
    - 功能模块: gongnengjieshao.md
#    - 关键特性: texingjieshao.md
    - 接口文档: api.md
  - 网络搭建:
    - 快速开始: run.md
version: v1.0.0
theme: readthedocs