site_name: Simpledger联盟区块链平台
nav:
  - 整体概述:
    - simpledger介绍: zhengtijieshao.md
  - 系统设计:
    - 功能模块: gongnengjieshao.md
#    - 关键特性: texingjieshao.md
    - 接口文档: rpc.md
#    - RPC接口: rpc.md
  - 网络搭建:
    - 环境要求: env.md
    - 快速开始: run.md
    - 节点管理: peer.md
    - 实用工具: tool.md
version: v1.0.0
theme: readthedocs
